# Generated by Django 3.0.7 on 2021-01-20 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_health', '0003_auto_20210120_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='build_time_iso',
            new_name='build_iso_time',
        ),
    ]
