# Generated by Django 3.0.7 on 2021-01-20 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_health', '0004_auto_20210120_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='fault_code',
            new_name='brew_faultCode',
        ),
        migrations.RenameField(
            model_name='build',
            old_name='task_id',
            new_name='brew_task_id',
        ),
        migrations.RenameField(
            model_name='build',
            old_name='build_id',
            new_name='build_0_id',
        ),
        migrations.RenameField(
            model_name='build',
            old_name='build_iso_time',
            new_name='build_time_iso',
        ),
        migrations.RenameField(
            model_name='build',
            old_name='build_commit_url_github',
            new_name='label_io_openshift_build_commit_url',
        ),
        migrations.RenameField(
            model_name='build',
            old_name='iso_time',
            new_name='time_iso',
        ),
    ]
